wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701102614.281618
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.16.0
      6: 4.32.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
